openapi: 3.1.0
info:
  title: Bokbasen LRM API
  description: Bokbasen LRM API
  version: 0.1.0

paths:
  /lorem/{urn}:
    get:
      description: Resolve URN representing a Resource returning its location in a Location header
      parameters:
        - in: path
          name: urn
          schema:
            type: string
          required: true
          description: The resource to retrieve by URN
          examples:
            work:
              value: urn:bb:work:89QPPRK1EDJPW835E8G64SBKEG
            contributor:
              value: urn:bb:contributor:J8VRQN45EH4C31VGV9V4V6WYK4
      responses:
        '303':
          description: See Other
          headers:
            Location:
              example: work/89QPPRK1EDJPW835E8G64SBKEG
              schema:
                type: string
        '400':
          description: Bad request. Resource URN must be valid.

        '404':
          description: A user with the specified ID was not found.

        '5XX':
          description: Unexpected error.