openapi: 3.1.0
info:
  title: Bokbasen LRM API
  description: Bokbasen LRM API
  version: 0.1.0

paths:
  /lorem/work/{id}:
    description: Work by id
    get:
      description: Get Work by id
      tags:
        - work
      operationId: getWork
      parameters:
        - in: path
          description: The work to retrieve by id
          name: id
          schema:
            type: string
          required: true
          example: "89QPPRK1EDJPW835E8G64SBKEG"

        - in: header
          description: Etag, the revision of the resource in the client cache
          name: If-None-Match
          schema:
            type: integer
          example: 3

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Work'

        '304':
          description: Not Modified

        '400':
          description: Bad request. Resource ID must be valid.

        '404':
          description: Not Found. A resource with the specified ID was not found.

        '5XX':
          description: Unexpected error.


components:
  schemas:

    Work:
      type: object
      properties:
        type:
          type: string
          enum:
            - work
        urn:
          type: string
          nullable: false
          readOnly: true

        languages:
          description: The language(s) of this work ISO 639-2/B
          example: ["nob", "nno"]
          type: array
          items:
            type: string
          readOnly: true
          nullable: false
        title:
          type: WorkTitle

    WorkTitle:
      type: object
      properties:
        main:
          type: string
        part:
          type: string
        number:
          type: string
        variants:
          type: array
          items:
            type: string